version: "3.9"
services:
  # app:
    # build: .
    # ports:
    #   - "8000:8000"
    # volumes:
    #   - ./app:/app/app
    # develop:
    #   # Create a `watch` configuration to update the app
    #   # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
    #   watch:
    #     # Sync the working directory with the `/app` directory in the container
    #     - action: sync
    #       path: .
    #       target: /app
    #       # Exclude the project virtual environment — it could be for a
    #       # different platform in the container
    #       ignore:
    #         - .venv/

    #     # Rebuild the image if dependencies change by checking uv.lock
    #     - action: rebuild
    #       path: ./uv.lock
    # depends_on:
    #   - mongo
    # environment:
    #   - MONGODB_URI=mongodb://mongo:27017/mydb

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/usr/share/nginx/html/
    ports:
      - "3000:80"

volumes:
  mongo_data: