# Example Instagram-style comments with sentiment labels
instagram_comments = [
    # Positive
    {"text": "Love this! So beautiful 😍", "sentiment": "positive"},
    {"text": "Amazing work! Keep it up! ✨", "sentiment": "positive"},
    {"text": "This made me smile 😊", "sentiment": "positive"},
    {"text": "So inspiring! 🌟", "sentiment": "positive"},
    {"text": "Perfect! 👌", "sentiment": "positive"},
    {"text": "Congrats! So happy for you! 🎉", "sentiment": "positive"},
    {"text": "You look stunning! 🔥", "sentiment": "positive"},
    {"text": "Best post today! 🙌", "sentiment": "positive"},
    {"text": "Sending positive vibes! 🙏", "sentiment": "positive"},
    {"text": "This is exactly what I needed to see! ❤️", "sentiment": "positive"},
    {"text": "Incredible talent! 🎨", "sentiment": "positive"},
    {"text": "So much fun! 😂", "sentiment": "positive"},
    {"text": "Yasss queen! Slay! 👑", "sentiment": "positive"},
    {"text": "Goals! 🙌 Keep up the amazing work!", "sentiment": "positive"},
    {"text": "This is everything! 🔥", "sentiment": "positive"},
    # Neutral
    {"text": "Interesting perspective.", "sentiment": "neutral"},
    {"text": "Where was this taken?", "sentiment": "neutral"},
    {"text": "What camera did you use?", "sentiment": "neutral"},
    {"text": "Noted.", "sentiment": "neutral"},
    {"text": "Is this a new filter?", "sentiment": "neutral"},
    {"text": "Okay.", "sentiment": "neutral"},
    {"text": "I see.", "sentiment": "neutral"},
    {"text": "Thanks for sharing.", "sentiment": "neutral"},
    {"text": "This is a picture of a cat.", "sentiment": "neutral"},
    {"text": "The weather looks nice there.", "sentiment": "neutral"},
    {"text": "That's a blue car.", "sentiment": "neutral"},
    {"text": "Seen.", "sentiment": "neutral"},
    {"text": "Acknowledged.", "sentiment": "neutral"},
    {"text": "Fair enough.", "sentiment": "neutral"},
    {"text": "Point taken.", "sentiment": "neutral"},
    # Negative
    {"text": "I don't really like this.", "sentiment": "negative"},
    {"text": "Not your best work, honestly.", "sentiment": "negative"},
    {"text": "This is kind of boring.", "sentiment": "negative"},
    {"text": "I disagree with this point.", "sentiment": "negative"},
    {"text": "This filter doesn't look good.", "sentiment": "negative"},
    {"text": "Not a fan.", "sentiment": "negative"},
    {"text": "Could be better.", "sentiment": "negative"},
    {"text": "This isn't very original.", "sentiment": "negative"},
    {"text": "I expected more.", "sentiment": "negative"},
    {"text": "Meh.", "sentiment": "negative"},
    {"text": "Unfollowing.", "sentiment": "negative"},
    {"text": "This is inaccurate.", "sentiment": "negative"},
    {"text": "Doesn't really work for me.", "sentiment": "negative"},
    {"text": "Needs improvement.", "sentiment": "negative"},
    {"text": "Underwhelming.", "sentiment": "negative"},
    # Toxic
    {"text": "You're so ugly, delete this.", "sentiment": "toxic"},
    {"text": "This is stupid, get a life.", "sentiment": "toxic"},
    {"text": "Nobody cares about your opinion.", "sentiment": "toxic"},
    {"text": "Go back where you came from.", "sentiment": "toxic"}, # Hate speech example
    {"text": "You're talentless and should quit.", "sentiment": "toxic"},
    {"text": "What an idiot.", "sentiment": "toxic"},
    {"text": "This is trash.", "sentiment": "toxic"},
    {"text": "I hope something bad happens to you.", "sentiment": "toxic"}, # Threat example
    # {"text": "Kill yourself.", "sentiment": "toxic"}, # Extreme example, maybe omit for safety
    {"text": "You're fat and disgusting.", "sentiment": "toxic"}, # Body shaming example
    {"text": "Fake and photoshopped.", "sentiment": "toxic"},
    {"text": "Absolute garbage content.", "sentiment": "toxic"},
    {"text": "Why are you even allowed online?", "sentiment": "toxic"},
    {"text": "Learn how to take a picture, moron.", "sentiment": "toxic"},
    {"text": "This is the dumbest thing I've ever seen.", "sentiment": "toxic"},
    {"text": "You should be ashamed.", "sentiment": "toxic"},
]